# Generated by Django 5.2.17 on 2026-09-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hiring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("mobile_number", models.CharField(max_length=20)),
                ("resume_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="hiring.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hunar_agent_id", models.CharField(max_length=255)),
                (
                    "call_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(default="NOT_STARTED", max_length=100)),
                (
                    "lifecycle_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "engagement_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "answered_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "call_ended_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("custom_data", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="hiring.job",
                    ),
                ),
            ],
        ),
    ]
